spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshare
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      expiration: 8640000
      secret: /FrOtYap9aBXCs1FZFzlVonzt8Lug0HmiXLaWpPtE9KLwpaLR9Zhah2kKw0s1iew
  mailing:
    from: veekthorcodes@gmail.com
    frontend:
      activation-url: http://localhost:4000/activate-account
